export enum SocietyCategory {
  ACADEMIC = 'ACADEMIC',
  CULTURAL = 'CULTURAL',
  TECHNICAL = 'TECHNICAL',
  SPORTS = 'SPORTS',
  VOLUNTEER = 'VOLUNTEER',
}

export enum MemberDesignation {
  PRESIDENT = 'PRESIDENT',
  VICE_PRESIDENT = 'VICE_PRESIDENT',
  GENERAL_SECRETARY = 'GENERAL_SECRETARY',
  ASSISTANT_GENERAL_SECRETARY = 'ASSISTANT_GENERAL_SECRETARY',
  TREASURER = 'TREASURER',
  EXECUTIVE_MEMBER = 'EXECUTIVE_MEMBER',
  MEMBER = 'MEMBER',
  ADVISOR = 'ADVISOR',
}
